export const SET_COUNTER = 'SET_COUNTER'
export const SET_CLEAR = 'SET_CLEAR'
export const SET_INCREMENT = 'SET_INCREMENT'
export const SET_DECREMENT = 'SET_DECREMENT'

export const PRESSED_HELLO_BUTTON = 'PRESSED_HELLO_BUTTON'